name = "dp1-feed-operator-api-dev"
main = "index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Variables for all environments
[vars]
ENVIRONMENT = "development"

# KV namespace bindings for storing JSON data
[[kv_namespaces]]
binding = "DP1_PLAYLISTS"
id = "626b74ca2b5b4606904cac7c4bbfd454"
preview_id = "648e8feef0f24832a01c372a79d76a0a"

[[kv_namespaces]]
binding = "DP1_PLAYLIST_GROUPS"
id = "df9f99f5d73d43f9a941859819cf0f29"
preview_id = "9a0626e294fa43f1b880b4432da55186"

# Production environment
[env.production]
name = "dp1-feed-operator-api-prod"
route = { pattern = "api.feed.feralfile.com/*", zone_name = "feralfile.com" }
[env.production.vars]
ENVIRONMENT = "production"

# Production KV namespaces
[[env.production.kv_namespaces]]
binding = "DP1_PLAYLISTS"
id = "626b74ca2b5b4606904cac7c4bbfd454"

[[env.production.kv_namespaces]]
binding = "DP1_PLAYLIST_GROUPS"
id = "df9f99f5d73d43f9a941859819cf0f29"

# Durable Objects (for real-time features - optional)
# [[durable_objects.bindings]]
# name = "PLAYLIST_SESSIONS"
# class_name = "PlaylistSession"

# AI binding (for future AI features - optional)
# [ai]
# binding = "AI"

# Analytics Engine (for usage tracking - optional)
# [[analytics_engine_datasets]]
# binding = "DP1_ANALYTICS"

# Rate limiting configuration
[limits]
cpu_ms = 30000

# Build configuration
[build]
command = "npm run build:worker"

# Secrets (set via wrangler secret put)
# API_SECRET - Bearer token secret
# ED25519_PRIVATE_KEY - Server signing key (REQUIRED)
# IPFS_GATEWAY_TOKEN - IPFS access token (optional) 