name = "dp1-feed-operator-api-dev"
main = "index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Variables for all environments
[vars]
ENVIRONMENT = "development"
SELF_HOSTED_DOMAINS = "dp1-feed-operator-api-dev.autonomy-system.workers.dev,localhost:8787"

# KV namespace bindings for storing JSON data
[[kv_namespaces]]
binding = "DP1_PLAYLISTS"
id = "626b74ca2b5b4606904cac7c4bbfd454"
preview_id = "6ccea1576def4fceb9da3f3cc450b46a"

[[kv_namespaces]]
binding = "DP1_PLAYLIST_GROUPS"
id = "df9f99f5d73d43f9a941859819cf0f29"
preview_id = "a46971c67a444a449651fd72a3adc46d"

[[kv_namespaces]]
binding = "DP1_PLAYLIST_ITEMS"
id = "0f215f359a50412f8717088448c6db2b"
preview_id = "5a79950f2bd843309902e582c9162cae"

# Production environment
[env.production]
name = "dp1-feed-operator-api-prod"
route = { pattern = "api.feed.feralfile.com/*", zone_name = "feralfile.com" }
[env.production.vars]
ENVIRONMENT = "production"
SELF_HOSTED_DOMAINS = "api.feed.feralfile.com, dp1-feed-operator-api-prod.autonomy-system.workers.dev"

# Production KV namespaces
[[env.production.kv_namespaces]]
binding = "DP1_PLAYLISTS"
id = "626b74ca2b5b4606904cac7c4bbfd454"

[[env.production.kv_namespaces]]
binding = "DP1_PLAYLIST_GROUPS"
id = "df9f99f5d73d43f9a941859819cf0f29"

[[env.production.kv_namespaces]]
binding = "DP1_PLAYLIST_ITEMS"
id = "0f215f359a50412f8717088448c6db2b"

# Durable Objects (for real-time features - optional)
# [[durable_objects.bindings]]
# name = "PLAYLIST_SESSIONS"
# class_name = "PlaylistSession"

# AI binding (for future AI features - optional)
# [ai]
# binding = "AI"

# Analytics Engine (for usage tracking - optional)
# [[analytics_engine_datasets]]
# binding = "DP1_ANALYTICS"

# Rate limiting configuration
[limits]
cpu_ms = 30000

# Build configuration
[build]
command = "npm run build:worker"

# Secrets (set via wrangler secret put)
# API_SECRET - Bearer token secret
# ED25519_PRIVATE_KEY - Server signing key (REQUIRED)
# IPFS_GATEWAY_TOKEN - IPFS access token (optional) 