name: Testing

on:
  push:
    branches: [main]
    paths:
      - 'prototype/server/**'
      - 'prototype/validator/**'
  pull_request:
    branches: [main]
    paths:
      - 'prototype/server/**'
      - 'prototype/validator/**'

jobs:
  # Detect which components changed
  changes:
    runs-on: ubuntu-latest
    outputs:
      server: ${{ steps.filter.outputs.server }}
      validator: ${{ steps.filter.outputs.validator }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            server:
              - 'prototype/server/**'
            validator:
              - 'prototype/validator/**'

  # Node.js/TypeScript testing for the server
  test-server:
    needs: changes
    if: ${{ needs.changes.outputs.server == 'true' }}
    runs-on: ubuntu-latest
    name: Server Tests

    defaults:
      run:
        working-directory: ./prototype/server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'prototype/server/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Start development server for integration tests
        run: |
          npm run dev:port &
          sleep 5

      - name: Run integration tests
        run: npm run test:api
        env:
          API_SECRET: test-api-secret

      - name: Stop development server
        run: pkill -f "wrangler dev" || true

  # Go testing for the validator
  test-validator:
    needs: changes
    if: ${{ needs.changes.outputs.validator == 'true' }}
    runs-on: ubuntu-latest
    name: Validator Tests

    defaults:
      run:
        working-directory: ./prototype/validator

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: 'prototype/validator/go.sum'

      - name: Download dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Run unit tests
        run: go test -v ./...

      - name: Run tests with race detection
        run: go test -race -v ./...

      - name: Run benchmarks
        run: go test -bench=. -benchmem ./...

      - name: Build project
        run: go build -v ./...
